// This file was generated by gir (https://github.com/gtk-rs/gir @ 5ec9961)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

use ffi;
use std::ffi::CStr;

lazy_static! {
    pub static ref MAP_CACHE_AUTO: &'static str = unsafe{CStr::from_ptr(ffi::OSM_GPS_MAP_CACHE_AUTO).to_str().unwrap()};
}
lazy_static! {
    pub static ref MAP_CACHE_DISABLED: &'static str = unsafe{CStr::from_ptr(ffi::OSM_GPS_MAP_CACHE_DISABLED).to_str().unwrap()};
}
lazy_static! {
    pub static ref MAP_CACHE_FRIENDLY: &'static str = unsafe{CStr::from_ptr(ffi::OSM_GPS_MAP_CACHE_FRIENDLY).to_str().unwrap()};
}
