// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use std::fmt;

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum MapKey_t {
    Fullscreen,
    Zoomin,
    Zoomout,
    Up,
    Down,
    Left,
    Right,
    Max,
#[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for MapKey_t {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "MapKey_t::{}", match *self {
            MapKey_t::Fullscreen => "Fullscreen",
            MapKey_t::Zoomin => "Zoomin",
            MapKey_t::Zoomout => "Zoomout",
            MapKey_t::Up => "Up",
            MapKey_t::Down => "Down",
            MapKey_t::Left => "Left",
            MapKey_t::Right => "Right",
            MapKey_t::Max => "Max",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for MapKey_t {
    type GlibType = ffi::OsmGpsMapKey_t;

    fn to_glib(&self) -> ffi::OsmGpsMapKey_t {
        match *self {
            MapKey_t::Fullscreen => ffi::OSM_GPS_MAP_KEY_FULLSCREEN,
            MapKey_t::Zoomin => ffi::OSM_GPS_MAP_KEY_ZOOMIN,
            MapKey_t::Zoomout => ffi::OSM_GPS_MAP_KEY_ZOOMOUT,
            MapKey_t::Up => ffi::OSM_GPS_MAP_KEY_UP,
            MapKey_t::Down => ffi::OSM_GPS_MAP_KEY_DOWN,
            MapKey_t::Left => ffi::OSM_GPS_MAP_KEY_LEFT,
            MapKey_t::Right => ffi::OSM_GPS_MAP_KEY_RIGHT,
            MapKey_t::Max => ffi::OSM_GPS_MAP_KEY_MAX,
            MapKey_t::__Unknown(value) => value,
}
    }
}

#[doc(hidden)]
impl FromGlib<ffi::OsmGpsMapKey_t> for MapKey_t {
    fn from_glib(value: ffi::OsmGpsMapKey_t) -> Self {
        skip_assert_initialized!();
        match value {
            0 => MapKey_t::Fullscreen,
            1 => MapKey_t::Zoomin,
            2 => MapKey_t::Zoomout,
            3 => MapKey_t::Up,
            4 => MapKey_t::Down,
            5 => MapKey_t::Left,
            6 => MapKey_t::Right,
            7 => MapKey_t::Max,
            value => MapKey_t::__Unknown(value),
}
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum MapSource_t {
    Null,
    Openstreetmap,
    OpenstreetmapRenderer,
    Openaerialmap,
    MapsForFree,
    Opencyclemap,
    OsmPublicTransport,
    GoogleStreet,
    GoogleSatellite,
    GoogleHybrid,
    VirtualEarthStreet,
    VirtualEarthSatellite,
    VirtualEarthHybrid,
    OsmcTrails,
    Last,
#[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for MapSource_t {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "MapSource_t::{}", match *self {
            MapSource_t::Null => "Null",
            MapSource_t::Openstreetmap => "Openstreetmap",
            MapSource_t::OpenstreetmapRenderer => "OpenstreetmapRenderer",
            MapSource_t::Openaerialmap => "Openaerialmap",
            MapSource_t::MapsForFree => "MapsForFree",
            MapSource_t::Opencyclemap => "Opencyclemap",
            MapSource_t::OsmPublicTransport => "OsmPublicTransport",
            MapSource_t::GoogleStreet => "GoogleStreet",
            MapSource_t::GoogleSatellite => "GoogleSatellite",
            MapSource_t::GoogleHybrid => "GoogleHybrid",
            MapSource_t::VirtualEarthStreet => "VirtualEarthStreet",
            MapSource_t::VirtualEarthSatellite => "VirtualEarthSatellite",
            MapSource_t::VirtualEarthHybrid => "VirtualEarthHybrid",
            MapSource_t::OsmcTrails => "OsmcTrails",
            MapSource_t::Last => "Last",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for MapSource_t {
    type GlibType = ffi::OsmGpsMapSource_t;

    fn to_glib(&self) -> ffi::OsmGpsMapSource_t {
        match *self {
            MapSource_t::Null => ffi::OSM_GPS_MAP_SOURCE_NULL,
            MapSource_t::Openstreetmap => ffi::OSM_GPS_MAP_SOURCE_OPENSTREETMAP,
            MapSource_t::OpenstreetmapRenderer => ffi::OSM_GPS_MAP_SOURCE_OPENSTREETMAP_RENDERER,
            MapSource_t::Openaerialmap => ffi::OSM_GPS_MAP_SOURCE_OPENAERIALMAP,
            MapSource_t::MapsForFree => ffi::OSM_GPS_MAP_SOURCE_MAPS_FOR_FREE,
            MapSource_t::Opencyclemap => ffi::OSM_GPS_MAP_SOURCE_OPENCYCLEMAP,
            MapSource_t::OsmPublicTransport => ffi::OSM_GPS_MAP_SOURCE_OSM_PUBLIC_TRANSPORT,
            MapSource_t::GoogleStreet => ffi::OSM_GPS_MAP_SOURCE_GOOGLE_STREET,
            MapSource_t::GoogleSatellite => ffi::OSM_GPS_MAP_SOURCE_GOOGLE_SATELLITE,
            MapSource_t::GoogleHybrid => ffi::OSM_GPS_MAP_SOURCE_GOOGLE_HYBRID,
            MapSource_t::VirtualEarthStreet => ffi::OSM_GPS_MAP_SOURCE_VIRTUAL_EARTH_STREET,
            MapSource_t::VirtualEarthSatellite => ffi::OSM_GPS_MAP_SOURCE_VIRTUAL_EARTH_SATELLITE,
            MapSource_t::VirtualEarthHybrid => ffi::OSM_GPS_MAP_SOURCE_VIRTUAL_EARTH_HYBRID,
            MapSource_t::OsmcTrails => ffi::OSM_GPS_MAP_SOURCE_OSMC_TRAILS,
            MapSource_t::Last => ffi::OSM_GPS_MAP_SOURCE_LAST,
            MapSource_t::__Unknown(value) => value,
}
    }
}

#[doc(hidden)]
impl FromGlib<ffi::OsmGpsMapSource_t> for MapSource_t {
    fn from_glib(value: ffi::OsmGpsMapSource_t) -> Self {
        skip_assert_initialized!();
        match value {
            0 => MapSource_t::Null,
            1 => MapSource_t::Openstreetmap,
            2 => MapSource_t::OpenstreetmapRenderer,
            3 => MapSource_t::Openaerialmap,
            4 => MapSource_t::MapsForFree,
            5 => MapSource_t::Opencyclemap,
            6 => MapSource_t::OsmPublicTransport,
            7 => MapSource_t::GoogleStreet,
            8 => MapSource_t::GoogleSatellite,
            9 => MapSource_t::GoogleHybrid,
            10 => MapSource_t::VirtualEarthStreet,
            11 => MapSource_t::VirtualEarthSatellite,
            12 => MapSource_t::VirtualEarthHybrid,
            13 => MapSource_t::OsmcTrails,
            14 => MapSource_t::Last,
            value => MapSource_t::__Unknown(value),
}
    }
}

