// This file was generated by gir (https://github.com/gtk-rs/gir @ bdc4404)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

use MapImage;
use MapKey_t;
use MapLayer;
use MapPoint;
use MapPolygon;
use MapSource_t;
use MapTrack;
use ffi;
use gdk;
use gdk_pixbuf;
use glib::StaticType;
use glib::Value;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use gtk;
use gtk_ffi;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem;
use std::mem::transmute;

glib_wrapper! {
    pub struct Map(Object<ffi::OsmGpsMap, ffi::OsmGpsMapClass>): [
        gtk::Widget => gtk_ffi::GtkWidget,
    ];

    match fn {
        get_type => || ffi::osm_gps_map_get_type(),
    }
}

impl Map {
    pub fn new() -> Map {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_none(ffi::osm_gps_map_new()).downcast_unchecked()
        }
    }

    pub fn get_default_cache_directory() -> Option<String> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osm_gps_map_get_default_cache_directory())
        }
    }

    pub fn source_get_copyright(source: MapSource_t) -> Option<String> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::osm_gps_map_source_get_copyright(source.to_glib()))
        }
    }

    pub fn source_get_friendly_name(source: MapSource_t) -> Option<String> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::osm_gps_map_source_get_friendly_name(source.to_glib()))
        }
    }

    pub fn source_get_image_format(source: MapSource_t) -> Option<String> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::osm_gps_map_source_get_image_format(source.to_glib()))
        }
    }

    pub fn source_get_max_zoom(source: MapSource_t) -> i32 {
        assert_initialized_main_thread!();
        unsafe {
            ffi::osm_gps_map_source_get_max_zoom(source.to_glib())
        }
    }

    pub fn source_get_min_zoom(source: MapSource_t) -> i32 {
        assert_initialized_main_thread!();
        unsafe {
            ffi::osm_gps_map_source_get_min_zoom(source.to_glib())
        }
    }

    pub fn source_get_repo_uri(source: MapSource_t) -> Option<String> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::osm_gps_map_source_get_repo_uri(source.to_glib()))
        }
    }

    pub fn source_is_valid(source: MapSource_t) -> bool {
        assert_initialized_main_thread!();
        unsafe {
            from_glib(ffi::osm_gps_map_source_is_valid(source.to_glib()))
        }
    }
}

impl Default for Map {
    fn default() -> Self {
        Self::new()
    }
}

pub trait MapExt: 'static {
    fn convert_geographic_to_screen(&self, pt: &mut MapPoint) -> (i32, i32);

    fn convert_screen_to_geographic(&self, pixel_x: i32, pixel_y: i32) -> MapPoint;

    fn download_cancel_all(&self);

    fn download_maps(&self, pt1: &mut MapPoint, pt2: &mut MapPoint, zoom_start: i32, zoom_end: i32);

    fn get_bbox(&self) -> (MapPoint, MapPoint);

    fn get_event_location(&self, event: &mut gdk::EventButton) -> Option<MapPoint>;

    fn get_scale(&self) -> f32;

    fn gps_add(&self, latitude: f32, longitude: f32, heading: f32);

    fn gps_clear(&self);

    fn gps_get_track(&self) -> Option<MapTrack>;

    fn image_add(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf) -> Option<MapImage>;

    fn image_add_with_alignment(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf, xalign: f32, yalign: f32) -> Option<MapImage>;

    fn image_add_with_alignment_z(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf, xalign: f32, yalign: f32, zorder: i32) -> Option<MapImage>;

    fn image_add_z(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf, zorder: i32) -> Option<MapImage>;

    fn image_remove(&self, image: &MapImage) -> bool;

    fn image_remove_all(&self);

    fn layer_add<P: IsA<MapLayer>>(&self, layer: &P);

    fn layer_remove<P: IsA<MapLayer>>(&self, layer: &P) -> bool;

    fn layer_remove_all(&self);

    fn map_redraw(&self) -> bool;

    fn map_redraw_idle(&self);

    fn polygon_add(&self, poly: &MapPolygon);

    fn polygon_remove(&self, poly: &MapPolygon) -> bool;

    fn polygon_remove_all(&self);

    fn scroll(&self, dx: i32, dy: i32);

    fn set_center(&self, latitude: f32, longitude: f32);

    fn set_center_and_zoom(&self, latitude: f32, longitude: f32, zoom: i32);

    fn set_keyboard_shortcut(&self, key: MapKey_t, keyval: u32);

    fn set_zoom(&self, zoom: i32) -> i32;

    fn set_zoom_offset(&self, zoom_offset: i32);

    fn track_add(&self, track: &MapTrack);

    fn track_remove(&self, track: &MapTrack) -> bool;

    fn track_remove_all(&self);

    fn zoom_fit_bbox(&self, latitude1: f32, latitude2: f32, longitude1: f32, longitude2: f32);

    fn zoom_in(&self) -> i32;

    fn zoom_out(&self) -> i32;

    fn get_property_auto_center(&self) -> bool;

    fn set_property_auto_center(&self, auto_center: bool);

    fn get_property_auto_center_threshold(&self) -> f32;

    fn set_property_auto_center_threshold(&self, auto_center_threshold: f32);

    fn get_property_auto_download(&self) -> bool;

    fn set_property_auto_download(&self, auto_download: bool);

    fn get_property_drag_limit(&self) -> i32;

    fn get_property_gps_track_highlight_radius(&self) -> i32;

    fn set_property_gps_track_highlight_radius(&self, gps_track_highlight_radius: i32);

    fn get_property_gps_track_point_radius(&self) -> i32;

    fn set_property_gps_track_point_radius(&self, gps_track_point_radius: i32);

    fn get_property_gps_track_width(&self) -> f32;

    fn set_property_gps_track_width(&self, gps_track_width: f32);

    fn get_property_image_format(&self) -> Option<String>;

    fn get_property_latitude(&self) -> f32;

    fn get_property_longitude(&self) -> f32;

    fn get_property_map_source(&self) -> i32;

    fn set_property_map_source(&self, map_source: i32);

    fn get_property_map_x(&self) -> i32;

    fn get_property_map_y(&self) -> i32;

    fn get_property_max_zoom(&self) -> i32;

    fn get_property_min_zoom(&self) -> i32;

    fn get_property_proxy_uri(&self) -> Option<String>;

    fn get_property_record_trip_history(&self) -> bool;

    fn set_property_record_trip_history(&self, record_trip_history: bool);

    fn get_property_repo_uri(&self) -> Option<String>;

    fn get_property_show_gps_point(&self) -> bool;

    fn set_property_show_gps_point(&self, show_gps_point: bool);

    fn get_property_show_trip_history(&self) -> bool;

    fn set_property_show_trip_history(&self, show_trip_history: bool);

    fn get_property_tile_cache(&self) -> Option<String>;

    fn set_property_tile_cache<'a, P: Into<Option<&'a str>>>(&self, tile_cache: P);

    fn get_property_tile_cache_base(&self) -> Option<String>;

    fn get_property_tile_zoom_offset(&self) -> i32;

    fn get_property_tiles_queued(&self) -> i32;

    fn get_property_user_agent(&self) -> Option<String>;

    fn set_property_user_agent<'a, P: Into<Option<&'a str>>>(&self, user_agent: P);

    fn get_property_zoom(&self) -> i32;

    fn connect_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_auto_center_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_auto_center_threshold_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_auto_download_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_gps_track_highlight_radius_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_gps_track_point_radius_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_gps_track_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_latitude_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_longitude_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_map_source_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_record_trip_history_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_show_gps_point_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_show_trip_history_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_tile_cache_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_tiles_queued_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_user_agent_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: 'static + IsA<Map>> MapExt for O {
    fn convert_geographic_to_screen(&self, pt: &mut MapPoint) -> (i32, i32) {
        unsafe {
            let mut pixel_x = mem::uninitialized();
            let mut pixel_y = mem::uninitialized();
            ffi::osm_gps_map_convert_geographic_to_screen(self.to_glib_none().0, pt.to_glib_none_mut().0, &mut pixel_x, &mut pixel_y);
            (pixel_x, pixel_y)
        }
    }

    fn convert_screen_to_geographic(&self, pixel_x: i32, pixel_y: i32) -> MapPoint {
        unsafe {
            let mut pt = MapPoint::uninitialized();
            ffi::osm_gps_map_convert_screen_to_geographic(self.to_glib_none().0, pixel_x, pixel_y, pt.to_glib_none_mut().0);
            pt
        }
    }

    fn download_cancel_all(&self) {
        unsafe {
            ffi::osm_gps_map_download_cancel_all(self.to_glib_none().0);
        }
    }

    fn download_maps(&self, pt1: &mut MapPoint, pt2: &mut MapPoint, zoom_start: i32, zoom_end: i32) {
        unsafe {
            ffi::osm_gps_map_download_maps(self.to_glib_none().0, pt1.to_glib_none_mut().0, pt2.to_glib_none_mut().0, zoom_start, zoom_end);
        }
    }

    fn get_bbox(&self) -> (MapPoint, MapPoint) {
        unsafe {
            let mut pt1 = MapPoint::uninitialized();
            let mut pt2 = MapPoint::uninitialized();
            ffi::osm_gps_map_get_bbox(self.to_glib_none().0, pt1.to_glib_none_mut().0, pt2.to_glib_none_mut().0);
            (pt1, pt2)
        }
    }

    fn get_event_location(&self, event: &mut gdk::EventButton) -> Option<MapPoint> {
        unsafe {
            from_glib_full(ffi::osm_gps_map_get_event_location(self.to_glib_none().0, event.to_glib_none_mut().0))
        }
    }

    fn get_scale(&self) -> f32 {
        unsafe {
            ffi::osm_gps_map_get_scale(self.to_glib_none().0)
        }
    }

    fn gps_add(&self, latitude: f32, longitude: f32, heading: f32) {
        unsafe {
            ffi::osm_gps_map_gps_add(self.to_glib_none().0, latitude, longitude, heading);
        }
    }

    fn gps_clear(&self) {
        unsafe {
            ffi::osm_gps_map_gps_clear(self.to_glib_none().0);
        }
    }

    fn gps_get_track(&self) -> Option<MapTrack> {
        unsafe {
            from_glib_none(ffi::osm_gps_map_gps_get_track(self.to_glib_none().0))
        }
    }

    fn image_add(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf) -> Option<MapImage> {
        unsafe {
            from_glib_full(ffi::osm_gps_map_image_add(self.to_glib_none().0, latitude, longitude, image.to_glib_none().0))
        }
    }

    fn image_add_with_alignment(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf, xalign: f32, yalign: f32) -> Option<MapImage> {
        unsafe {
            from_glib_full(ffi::osm_gps_map_image_add_with_alignment(self.to_glib_none().0, latitude, longitude, image.to_glib_none().0, xalign, yalign))
        }
    }

    fn image_add_with_alignment_z(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf, xalign: f32, yalign: f32, zorder: i32) -> Option<MapImage> {
        unsafe {
            from_glib_full(ffi::osm_gps_map_image_add_with_alignment_z(self.to_glib_none().0, latitude, longitude, image.to_glib_none().0, xalign, yalign, zorder))
        }
    }

    fn image_add_z(&self, latitude: f32, longitude: f32, image: &gdk_pixbuf::Pixbuf, zorder: i32) -> Option<MapImage> {
        unsafe {
            from_glib_full(ffi::osm_gps_map_image_add_z(self.to_glib_none().0, latitude, longitude, image.to_glib_none().0, zorder))
        }
    }

    fn image_remove(&self, image: &MapImage) -> bool {
        unsafe {
            from_glib(ffi::osm_gps_map_image_remove(self.to_glib_none().0, image.to_glib_none().0))
        }
    }

    fn image_remove_all(&self) {
        unsafe {
            ffi::osm_gps_map_image_remove_all(self.to_glib_none().0);
        }
    }

    fn layer_add<P: IsA<MapLayer>>(&self, layer: &P) {
        unsafe {
            ffi::osm_gps_map_layer_add(self.to_glib_none().0, layer.to_glib_none().0);
        }
    }

    fn layer_remove<P: IsA<MapLayer>>(&self, layer: &P) -> bool {
        unsafe {
            from_glib(ffi::osm_gps_map_layer_remove(self.to_glib_none().0, layer.to_glib_none().0))
        }
    }

    fn layer_remove_all(&self) {
        unsafe {
            ffi::osm_gps_map_layer_remove_all(self.to_glib_none().0);
        }
    }

    fn map_redraw(&self) -> bool {
        unsafe {
            from_glib(ffi::osm_gps_map_map_redraw(self.to_glib_none().0))
        }
    }

    fn map_redraw_idle(&self) {
        unsafe {
            ffi::osm_gps_map_map_redraw_idle(self.to_glib_none().0);
        }
    }

    fn polygon_add(&self, poly: &MapPolygon) {
        unsafe {
            ffi::osm_gps_map_polygon_add(self.to_glib_none().0, poly.to_glib_none().0);
        }
    }

    fn polygon_remove(&self, poly: &MapPolygon) -> bool {
        unsafe {
            from_glib(ffi::osm_gps_map_polygon_remove(self.to_glib_none().0, poly.to_glib_none().0))
        }
    }

    fn polygon_remove_all(&self) {
        unsafe {
            ffi::osm_gps_map_polygon_remove_all(self.to_glib_none().0);
        }
    }

    fn scroll(&self, dx: i32, dy: i32) {
        unsafe {
            ffi::osm_gps_map_scroll(self.to_glib_none().0, dx, dy);
        }
    }

    fn set_center(&self, latitude: f32, longitude: f32) {
        unsafe {
            ffi::osm_gps_map_set_center(self.to_glib_none().0, latitude, longitude);
        }
    }

    fn set_center_and_zoom(&self, latitude: f32, longitude: f32, zoom: i32) {
        unsafe {
            ffi::osm_gps_map_set_center_and_zoom(self.to_glib_none().0, latitude, longitude, zoom);
        }
    }

    fn set_keyboard_shortcut(&self, key: MapKey_t, keyval: u32) {
        unsafe {
            ffi::osm_gps_map_set_keyboard_shortcut(self.to_glib_none().0, key.to_glib(), keyval);
        }
    }

    fn set_zoom(&self, zoom: i32) -> i32 {
        unsafe {
            ffi::osm_gps_map_set_zoom(self.to_glib_none().0, zoom)
        }
    }

    fn set_zoom_offset(&self, zoom_offset: i32) {
        unsafe {
            ffi::osm_gps_map_set_zoom_offset(self.to_glib_none().0, zoom_offset);
        }
    }

    fn track_add(&self, track: &MapTrack) {
        unsafe {
            ffi::osm_gps_map_track_add(self.to_glib_none().0, track.to_glib_none().0);
        }
    }

    fn track_remove(&self, track: &MapTrack) -> bool {
        unsafe {
            from_glib(ffi::osm_gps_map_track_remove(self.to_glib_none().0, track.to_glib_none().0))
        }
    }

    fn track_remove_all(&self) {
        unsafe {
            ffi::osm_gps_map_track_remove_all(self.to_glib_none().0);
        }
    }

    fn zoom_fit_bbox(&self, latitude1: f32, latitude2: f32, longitude1: f32, longitude2: f32) {
        unsafe {
            ffi::osm_gps_map_zoom_fit_bbox(self.to_glib_none().0, latitude1, latitude2, longitude1, longitude2);
        }
    }

    fn zoom_in(&self) -> i32 {
        unsafe {
            ffi::osm_gps_map_zoom_in(self.to_glib_none().0)
        }
    }

    fn zoom_out(&self) -> i32 {
        unsafe {
            ffi::osm_gps_map_zoom_out(self.to_glib_none().0)
        }
    }

    fn get_property_auto_center(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bauto-center\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_auto_center(&self, auto_center: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bauto-center\0".as_ptr() as *const _, Value::from(&auto_center).to_glib_none().0);
        }
    }

    fn get_property_auto_center_threshold(&self) -> f32 {
        unsafe {
            let mut value = Value::from_type(<f32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bauto-center-threshold\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_auto_center_threshold(&self, auto_center_threshold: f32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bauto-center-threshold\0".as_ptr() as *const _, Value::from(&auto_center_threshold).to_glib_none().0);
        }
    }

    fn get_property_auto_download(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bauto-download\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_auto_download(&self, auto_download: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bauto-download\0".as_ptr() as *const _, Value::from(&auto_download).to_glib_none().0);
        }
    }

    fn get_property_drag_limit(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bdrag-limit\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_gps_track_highlight_radius(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bgps-track-highlight-radius\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_gps_track_highlight_radius(&self, gps_track_highlight_radius: i32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bgps-track-highlight-radius\0".as_ptr() as *const _, Value::from(&gps_track_highlight_radius).to_glib_none().0);
        }
    }

    fn get_property_gps_track_point_radius(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bgps-track-point-radius\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_gps_track_point_radius(&self, gps_track_point_radius: i32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bgps-track-point-radius\0".as_ptr() as *const _, Value::from(&gps_track_point_radius).to_glib_none().0);
        }
    }

    fn get_property_gps_track_width(&self) -> f32 {
        unsafe {
            let mut value = Value::from_type(<f32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bgps-track-width\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_gps_track_width(&self, gps_track_width: f32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bgps-track-width\0".as_ptr() as *const _, Value::from(&gps_track_width).to_glib_none().0);
        }
    }

    fn get_property_image_format(&self) -> Option<String> {
        unsafe {
            let mut value = Value::from_type(<String as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bimage-format\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get()
        }
    }

    fn get_property_latitude(&self) -> f32 {
        unsafe {
            let mut value = Value::from_type(<f32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "blatitude\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_longitude(&self) -> f32 {
        unsafe {
            let mut value = Value::from_type(<f32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "blongitude\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_map_source(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bmap-source\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_map_source(&self, map_source: i32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bmap-source\0".as_ptr() as *const _, Value::from(&map_source).to_glib_none().0);
        }
    }

    fn get_property_map_x(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bmap-x\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_map_y(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bmap-y\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_max_zoom(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bmax-zoom\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_min_zoom(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bmin-zoom\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_proxy_uri(&self) -> Option<String> {
        unsafe {
            let mut value = Value::from_type(<String as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bproxy-uri\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get()
        }
    }

    fn get_property_record_trip_history(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "brecord-trip-history\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_record_trip_history(&self, record_trip_history: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "brecord-trip-history\0".as_ptr() as *const _, Value::from(&record_trip_history).to_glib_none().0);
        }
    }

    fn get_property_repo_uri(&self) -> Option<String> {
        unsafe {
            let mut value = Value::from_type(<String as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "brepo-uri\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get()
        }
    }

    fn get_property_show_gps_point(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bshow-gps-point\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_show_gps_point(&self, show_gps_point: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bshow-gps-point\0".as_ptr() as *const _, Value::from(&show_gps_point).to_glib_none().0);
        }
    }

    fn get_property_show_trip_history(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bshow-trip-history\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_show_trip_history(&self, show_trip_history: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bshow-trip-history\0".as_ptr() as *const _, Value::from(&show_trip_history).to_glib_none().0);
        }
    }

    fn get_property_tile_cache(&self) -> Option<String> {
        unsafe {
            let mut value = Value::from_type(<String as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "btile-cache\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get()
        }
    }

    fn set_property_tile_cache<'a, P: Into<Option<&'a str>>>(&self, tile_cache: P) {
        let tile_cache = tile_cache.into();
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "btile-cache\0".as_ptr() as *const _, Value::from(tile_cache).to_glib_none().0);
        }
    }

    fn get_property_tile_cache_base(&self) -> Option<String> {
        unsafe {
            let mut value = Value::from_type(<String as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "btile-cache-base\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get()
        }
    }

    fn get_property_tile_zoom_offset(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "btile-zoom-offset\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_tiles_queued(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "btiles-queued\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn get_property_user_agent(&self) -> Option<String> {
        unsafe {
            let mut value = Value::from_type(<String as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "buser-agent\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get()
        }
    }

    fn set_property_user_agent<'a, P: Into<Option<&'a str>>>(&self, user_agent: P) {
        let user_agent = user_agent.into();
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "buser-agent\0".as_ptr() as *const _, Value::from(user_agent).to_glib_none().0);
        }
    }

    fn get_property_zoom(&self) -> i32 {
        unsafe {
            let mut value = Value::from_type(<i32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bzoom\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn connect_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "changed",
                transmute(changed_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_auto_center_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::auto-center",
                transmute(notify_auto_center_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_auto_center_threshold_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::auto-center-threshold",
                transmute(notify_auto_center_threshold_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_auto_download_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::auto-download",
                transmute(notify_auto_download_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_gps_track_highlight_radius_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::gps-track-highlight-radius",
                transmute(notify_gps_track_highlight_radius_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_gps_track_point_radius_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::gps-track-point-radius",
                transmute(notify_gps_track_point_radius_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_gps_track_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::gps-track-width",
                transmute(notify_gps_track_width_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_latitude_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::latitude",
                transmute(notify_latitude_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_longitude_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::longitude",
                transmute(notify_longitude_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_map_source_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::map-source",
                transmute(notify_map_source_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_record_trip_history_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::record-trip-history",
                transmute(notify_record_trip_history_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_show_gps_point_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::show-gps-point",
                transmute(notify_show_gps_point_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_show_trip_history_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::show-trip-history",
                transmute(notify_show_trip_history_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_tile_cache_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::tile-cache",
                transmute(notify_tile_cache_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_tiles_queued_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::tiles-queued",
                transmute(notify_tiles_queued_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_user_agent_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::user-agent",
                transmute(notify_user_agent_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

unsafe extern "C" fn changed_trampoline<P>(this: *mut ffi::OsmGpsMap, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_auto_center_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_auto_center_threshold_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_auto_download_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_gps_track_highlight_radius_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_gps_track_point_radius_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_gps_track_width_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_latitude_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_longitude_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_map_source_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_record_trip_history_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_show_gps_point_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_show_trip_history_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_tile_cache_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_tiles_queued_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_user_agent_trampoline<P>(this: *mut ffi::OsmGpsMap, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Map> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Map::from_glib_borrow(this).downcast_unchecked())
}

impl fmt::Display for Map {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Map")
    }
}
