// This file was generated by gir (https://github.com/gtk-rs/gir @ bdc4404)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

use MapPoint;
use ffi;
use gdk;
use glib::StaticType;
use glib::Value;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use libc;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib_wrapper! {
    pub struct MapTrack(Object<ffi::OsmGpsMapTrack, ffi::OsmGpsMapTrackClass>);

    match fn {
        get_type => || ffi::osm_gps_map_track_get_type(),
    }
}

impl MapTrack {
    pub fn new() -> MapTrack {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osm_gps_map_track_new())
        }
    }
}

impl Default for MapTrack {
    fn default() -> Self {
        Self::new()
    }
}

pub trait MapTrackExt: 'static {
    //fn add_point(&self, point: &MapPoint);

    fn get_color(&self, color: &mut gdk::RGBA);

    fn get_length(&self) -> f64;

    fn get_point(&self, pos: i32) -> Option<MapPoint>;

    fn get_points(&self) -> Vec<MapPoint>;

    fn insert_point(&self, np: &mut MapPoint, pos: i32);

    fn n_points(&self) -> i32;

    fn remove_point(&self, pos: i32);

    fn set_color(&self, color: &mut gdk::RGBA);

    fn get_property_alpha(&self) -> f32;

    fn set_property_alpha(&self, alpha: f32);

    fn get_property_editable(&self) -> bool;

    fn set_property_editable(&self, editable: bool);

    fn get_property_line_width(&self) -> f32;

    fn set_property_line_width(&self, line_width: f32);

    //fn get_property_track(&self) -> /*Unimplemented*/Fundamental: Pointer;

    fn get_property_visible(&self) -> bool;

    fn set_property_visible(&self, visible: bool);

    fn connect_point_added<F: Fn(&Self, &MapPoint) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_point_changed<F: Fn(&Self, i32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_point_inserted<F: Fn(&Self, i32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_point_removed<F: Fn(&Self, i32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_alpha_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_color_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_editable_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_line_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_visible_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: 'static + IsA<MapTrack>> MapTrackExt for O {
    //fn add_point(&self, point: &MapPoint) {
    //    unsafe { TODO: call ffi::osm_gps_map_track_add_point() }
    //}

    fn get_color(&self, color: &mut gdk::RGBA) {
        unsafe {
            ffi::osm_gps_map_track_get_color(self.to_glib_none().0, color.to_glib_none_mut().0);
        }
    }

    fn get_length(&self) -> f64 {
        unsafe {
            ffi::osm_gps_map_track_get_length(self.to_glib_none().0)
        }
    }

    fn get_point(&self, pos: i32) -> Option<MapPoint> {
        unsafe {
            from_glib_full(ffi::osm_gps_map_track_get_point(self.to_glib_none().0, pos))
        }
    }

    fn get_points(&self) -> Vec<MapPoint> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::osm_gps_map_track_get_points(self.to_glib_none().0))
        }
    }

    fn insert_point(&self, np: &mut MapPoint, pos: i32) {
        unsafe {
            ffi::osm_gps_map_track_insert_point(self.to_glib_none().0, np.to_glib_none_mut().0, pos);
        }
    }

    fn n_points(&self) -> i32 {
        unsafe {
            ffi::osm_gps_map_track_n_points(self.to_glib_none().0)
        }
    }

    fn remove_point(&self, pos: i32) {
        unsafe {
            ffi::osm_gps_map_track_remove_point(self.to_glib_none().0, pos);
        }
    }

    fn set_color(&self, color: &mut gdk::RGBA) {
        unsafe {
            ffi::osm_gps_map_track_set_color(self.to_glib_none().0, color.to_glib_none_mut().0);
        }
    }

    fn get_property_alpha(&self) -> f32 {
        unsafe {
            let mut value = Value::from_type(<f32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "balpha\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_alpha(&self, alpha: f32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "balpha\0".as_ptr() as *const _, Value::from(&alpha).to_glib_none().0);
        }
    }

    fn get_property_editable(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "beditable\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_editable(&self, editable: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "beditable\0".as_ptr() as *const _, Value::from(&editable).to_glib_none().0);
        }
    }

    fn get_property_line_width(&self) -> f32 {
        unsafe {
            let mut value = Value::from_type(<f32 as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bline-width\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_line_width(&self, line_width: f32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bline-width\0".as_ptr() as *const _, Value::from(&line_width).to_glib_none().0);
        }
    }

    //fn get_property_track(&self) -> /*Unimplemented*/Fundamental: Pointer {
    //    unsafe {
    //        let mut value = Value::from_type(</*Unknown type*/ as StaticType>::static_type());
    //        gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "btrack\0".as_ptr() as *const _, value.to_glib_none_mut().0);
    //        value.get().unwrap()
    //    }
    //}

    fn get_property_visible(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bvisible\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().unwrap()
        }
    }

    fn set_property_visible(&self, visible: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut gobject_ffi::GObject, "bvisible\0".as_ptr() as *const _, Value::from(&visible).to_glib_none().0);
        }
    }

    fn connect_point_added<F: Fn(&Self, &MapPoint) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self, &MapPoint) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "point-added",
                transmute(point_added_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_point_changed<F: Fn(&Self, i32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self, i32) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "point-changed",
                transmute(point_changed_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_point_inserted<F: Fn(&Self, i32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self, i32) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "point-inserted",
                transmute(point_inserted_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_point_removed<F: Fn(&Self, i32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self, i32) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "point-removed",
                transmute(point_removed_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_alpha_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::alpha",
                transmute(notify_alpha_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_color_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::color",
                transmute(notify_color_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_editable_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::editable",
                transmute(notify_editable_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_line_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::line-width",
                transmute(notify_line_width_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_visible_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0 as *mut _, "notify::visible",
                transmute(notify_visible_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

unsafe extern "C" fn point_added_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, arg1: *mut ffi::OsmGpsMapPoint, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P, &MapPoint) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked(), &from_glib_borrow(arg1))
}

unsafe extern "C" fn point_changed_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, object: libc::c_int, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P, i32) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked(), object)
}

unsafe extern "C" fn point_inserted_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, object: libc::c_int, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P, i32) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked(), object)
}

unsafe extern "C" fn point_removed_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, object: libc::c_int, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P, i32) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked(), object)
}

unsafe extern "C" fn notify_alpha_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_color_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_editable_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_line_width_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_visible_trampoline<P>(this: *mut ffi::OsmGpsMapTrack, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<MapTrack> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&MapTrack::from_glib_borrow(this).downcast_unchecked())
}

impl fmt::Display for MapTrack {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "MapTrack")
    }
}
