// This file was generated by gir (https://github.com/gtk-rs/gir @ 5ec9961)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

mod map;
pub use self::map::Map;
pub use self::map::MapExt;

mod map_image;
pub use self::map_image::MapImage;
pub use self::map_image::MapImageExt;

mod map_layer;
pub use self::map_layer::MapLayer;
pub use self::map_layer::MapLayerExt;

mod map_osd;
pub use self::map_osd::MapOsd;
pub use self::map_osd::MapOsdExt;

mod map_polygon;
pub use self::map_polygon::MapPolygon;
pub use self::map_polygon::MapPolygonExt;

mod map_track;
pub use self::map_track::MapTrack;
pub use self::map_track::MapTrackExt;

mod map_point;
pub use self::map_point::MapPoint;

mod enums;
pub use self::enums::MapKey_t;
pub use self::enums::MapSource_t;

#[doc(hidden)]
pub mod traits {
    pub use super::MapExt;
    pub use super::MapImageExt;
    pub use super::MapLayerExt;
    pub use super::MapOsdExt;
    pub use super::MapPolygonExt;
    pub use super::MapTrackExt;
}
